name: Release to PyPi

on:
  release:
    types:
      - created
  workflow_call:
    secrets:
      PYPI_TOKEN:
        description: 'PyPi token'
        required: true

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install poetry
      run: pipx install poetry
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
        cache: 'poetry'
    - name: Publish package
      env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      run: |
          poetry config pypi-token.pypi $PYPI_TOKEN
          poetry publish --build
